# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'

target "Twitter" do

pod "BDBOAuth1Manager" , '=1.4.1'
# pod 'AFNetworking', '=2.4.1'
pod 'AFNetworking'
pod 'MBProgressHUD', '=0.9'
pod 'SDWebImage', '~>3.8'

end

target "TwitterTests" do

end

target "TwitterUITests" do

end

